name: blog-types
version: 0.1.0.0
github: "stackbuilders/compose-2019"
license: MIT
author: "Diego Balseiro"
maintainer: "dbalseiro@stackbuilders.com"
copyright: "2019 Stack Builders"

extra-source-files:
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/stackbuilders/compose-2019#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Werror

library:
  source-dirs: src
  dependencies:
    - aeson
    - http-api-data
    - text
