name: blog-server
version: 1.0
github: "stackbuilders/compose-2019"
license: MIT
author: "Diego Balseiro"
maintainer: "dbalseiro@gmail.com"
copyright: "2019 Stack Builders"

extra-source-files:
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/stackbuilders/compose-2019#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Werror

library:
  source-dirs: src
  dependencies:
    - aeson
    - servant-server
    - http-types
    - stm
    - wai
    - wai-cors
    - warp
    - blog-types

executables:
  blog-server-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - blog-server

tests:
  blog-types-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - blog-server
